### ISSUE TITLE
Package can't be installed using pip

### ISSUE THREAD

**Issue by andreabedini** [shanahanjrs/xmltojson#1]
```
$ pip3 install xmltojson
Collecting xmltojson
  Using cached xmltojson-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8t/b6yfjsvs5nqf44jcyfppm7bw0000gn/T/pip-build-eoo9ou1o/xmltojson/setup.py", line 2, in <module>
        import xmltojson
      File "/private/var/folders/8t/b6yfjsvs5nqf44jcyfppm7bw0000gn/T/pip-build-eoo9ou1o/xmltojson/xmltojson.py", line 21, in <module>
        import xmltodict
    ModuleNotFoundError: No module named 'xmltodict'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8t/b6yfjsvs5nqf44jcyfppm7bw0000gn/T/pip-build-eoo9ou1o/xmltojson/
```

You can't import `xmltodict` in `setup.py` :) because it is not installed yet

I might be able to send a PR when I have time.

**Comment by kislyuk** [comment]
@shanahanjrs if you're not going to maintain this package, can you please unpublish it from PyPI?

**Comment by andreabedini** [comment]
oh, I had forgotten about this! I clearly had no time 😹 the solutions is simple though: move the metadata from `xmltodict.py` to `setup.py`, and remove that `import xmltodict`.

**Comment by shanahanjrs** [comment]
Forgot about this, fixed. Will update in pypi when I can.

**Comment by shanahanjrs** [comment]
Pushed. If it works for you now ill close this issue, thanks for offering to fix it @andreabedini

**Comment by andreabedini** [comment]
LGTM! Thanks @shanahanjrs <3

**Comment by kislyuk** [comment]
Thanks.
